- name: install yum_repository epel
  yum_repository:
    name: epel
    description: Extra Packages for Enterprise Linux
    mirrorlist: "http://mirrors.fedoraproject.org/mirrorlist?repo=epel-{{ hostvars[inventory_hostname].ansible_distribution_major_version }}&arch=$basearch"
    gpgkey: "http://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ hostvars[inventory_hostname].ansible_distribution_major_version }}"

- name: install yum xxx
  yum:
    name:
      - curl
      - nss
      - git
      - ncdu
      - htop
      - crontabs
    enablerepo: "*"
    state: latest
